netgusto_baikal_core:
    resource: "@NetgustoBaikalCoreBundle/Resources/config/routing.yml"
    prefix:   /

netgusto_baikal_json_api:
    resource: "@NetgustoBaikalJsonApiBundle/Resources/config/routing.yml"
    prefix:   /api/json/

netgusto_baikal_frontend:
    resource: "@NetgustoBaikalFrontendBundle/Resources/config/routing.yml"
    prefix:   /

netgusto_baikal_dav_services:
    resource: "@NetgustoBaikalDavServicesBundle/Resources/config/routing.yml"
    prefix:   /dav/

netgusto_baikal_admin:
    resource: "@NetgustoBaikalAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/