parameters:
#    netgusto_baikal_admin.example.class: Netgusto\Baikal\AdminBundle\Example

services:
#    netgusto_baikal_admin.example:
#        class: %netgusto_baikal_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
